variables:
  OBS_PROJECT: "home:krzysztof.wasieczko"
  OBS_PACKAGE: "dattobd"
  OBS_TARGET_DISTRO: "null"

before_script:
  - cd ..; tar -c -z --exclude-vcs -v -f ${CI_PROJECT_NAME}.tar.gz ${CI_PROJECT_NAME}; cd $CI_PROJECT_NAME
  - export PARENT_VERSION=$(rpmspec -q --srpm --qf '%{version}' dist/${CI_PROJECT_NAME}.spec)

obsrelease:
  stage: obs
  tags:
    - docker-throttled
  script:
    - echo "TEST HAS STARTED"
    - obsctl tarimport -f ../${CI_PROJECT_NAME}.tar.gz -o $CI_PROJECT_NAMESPACE -n $CI_PROJECT_NAME -t $CI_COMMIT_TAG -R $CI_COMMIT_SHA -B $CI_COMMIT_REF_NAME -s $OBS_PROJECT -p $OBS_PACKAGE -T git -i
  only:
    - branches
